import { useEffect, useId, useMemo, useState } from 'react'
import { isLiteMode } from '../lib/perf'
import { sigilSvg, type SigilMood } from '../lib/sigil'

interface SigilProps {
  mood: SigilMood
  size: number
  strength?: number
  arc?: boolean
  hot?: boolean
  strokeBoost?: number
  crisp?: boolean
  className?: string
}

function usePrefersReducedMotion(): boolean {
  const [reduced, setReduced] = useState(() => {
    try {
      return window.matchMedia('(prefers-reduced-motion: reduce)').matches
    } catch {
      return false
    }
  })

  useEffect(() => {
    let query: MediaQueryList
    try {
      query = window.matchMedia('(prefers-reduced-motion: reduce)')
    } catch {
      return
    }
    const listener = (event: MediaQueryListEvent): void => setReduced(event.matches)
    query.addEventListener('change', listener)
    return () => query.removeEventListener('change', listener)
  }, [])

  return reduced
}

/**
 * Astrolabe sigil (DESIGN.md B6). The SVG is generated by our own pure module
 * (numbers only, never user data), so dangerouslySetInnerHTML is safe here.
 */
export function Sigil({ mood, size, strength = 0, arc, hot, strokeBoost, crisp, className }: SigilProps) {
  const reactId = useId()
  const idPrefix = useMemo(() => `sigil-${reactId.replace(/[^a-zA-Z0-9_-]/g, '')}`, [reactId])
  const reduced = usePrefersReducedMotion()
  const animate = !reduced && !isLiteMode()

  const html = useMemo(
    () => sigilSvg({ mood, strength, idPrefix, arc, hot, animate, strokeBoost, crisp }),
    [mood, strength, idPrefix, arc, hot, animate, strokeBoost, crisp],
  )

  return (
    <span
      className={className ? `sigil ${className}` : 'sigil'}
      style={{ width: size, height: size }}
      aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
